In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [3]:
#Create a numpy array
#1. Create a list
#2. Convert it into a numpy array

my_list = [1,2,3,4,5]

my_numpy_array = np.array(my_list)

print(my_numpy_array)

[1 2 3 4 5]


In [5]:
second_list = [6,7,8,9,10]

#Create a 2-Dimensional numpy array by nesting lists in np.array function

two_d_array = np.array([my_list, second_list])

print (two_d_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
#Check the total number of elements in a numpy array with .size attribute
two_d_array.size

10

In [10]:
#Check the dimension of the numpy array 
two_d_array.shape

(2, 5)

In [9]:
#Check the type of data stored in  a numpy array
two_d_array.dtype

dtype('int64')

In [11]:
#Create a identity matrix 

np.identity(n = 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
#Create a numpy array with N rows, M columns and position of diagonal values in K
np.eye(N=3, M=5, k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [7]:
#To create a numpy array filled with ones, we can use np.ones(shape = [2, 4]). this will create 
# a matrix with 2 rows and 4 columns , all elements as 1

np.ones(shape = [2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
#This will create a numpy array with 3 rows and 4 columns filled with zeroes.
np.zeros(shape = [3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#Indexing in numpy arrays

one_d_array = np.array([1,2,3,4,5,6])

one_d_array[0]

1

In [10]:
#Slicing in numpy array
one_d_array[0:4]

array([1, 2, 3, 4])

In [13]:
one_d_array[:4]

array([1, 2, 3, 4])

In [14]:
one_d_array[3:]


array([4, 5, 6])

In [20]:
#Return all the elements in the array except the last one element
one_d_array[:-1]

array([1, 2, 3, 4, 5])

In [21]:
#Reverse the numpy array
one_d_array[::-1]

array([6, 5, 4, 3, 2, 1])

In [7]:
#Create a two d array

two_d_arr = np.array([one_d_array , one_d_array + 3, one_d_array + 6])

print (two_d_arr)

[[ 1  2  3  4  5  6]
 [ 4  5  6  7  8  9]
 [ 7  8  9 10 11 12]]


In [25]:
#Performing indexing and slicing on a two d array
#Print the element from 1st row and 4th column

two_d_arr[1,4] 

8

In [27]:
two_d_arr[1:, 4:]

array([[ 8,  9],
       [11, 12]])

In [30]:
two_d_arr[::-1, ::-1]

array([[12, 11, 10,  9,  8,  7],
       [ 9,  8,  7,  6,  5,  4],
       [ 6,  5,  4,  3,  2,  1]])

In [31]:
#Reshaping an array , here we convert the above 3 * 6 array into 6 * 3 array

reshaped_arr = np.reshape(two_d_arr , newshape=(6,3))
print (reshaped_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 4  5  6]
 [ 7  8  9]
 [ 7  8  9]
 [10 11 12]]


In [12]:
#Concatenate two arrays
array_to_join = ([[10,20,30] , [40,50,60] , [70,80,90]])

np.concatenate((two_d_arr, array_to_join), axis = 1)

array([[ 1,  2,  3,  4,  5,  6, 10, 20, 30],
       [ 4,  5,  6,  7,  8,  9, 40, 50, 60],
       [ 7,  8,  9, 10, 11, 12, 70, 80, 90]])

In [13]:
first_array = np.array([1,2,3])
second_array = np.array([3,4,5])
print (first_array + second_array)

[4 6 8]


In [17]:
new_arr = np.array([1,2,3])
new_arr * new_arr

array([1, 4, 9])

In [18]:
new2_arr = np.array([3,4,5,6])
new2_arr ** new2_arr

array([   27,   256,  3125, 46656])

In [19]:
np.mean(new_arr)

2.0

In [20]:
np.median(new_arr)

2.0

In [22]:
np.mean((two_d_arr), axis = 1)

array([3.5, 6.5, 9.5])

In [23]:
#To find the standard deviation from the elements in the numpy array

np.std(two_d_arr)

2.9860788111948193

In [24]:
#Adding up the elements along the rows , there are 3 rows, hence 3 values for each row
np.sum(two_d_arr, axis = 1)

array([21, 39, 57])

In [25]:
#Adding up the elements along the columns, there are 6 columns, 6 values for each column
np.sum(two_d_arr , axis = 0)

array([12, 15, 18, 21, 24, 27])

In [26]:
#To find the logarithmic 

np.log(two_d_arr)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
        1.79175947],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015, 2.07944154,
        2.19722458],
       [1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527,
        2.48490665]])

In [27]:
#To find the square root of each element in the array

np.sqrt(two_d_arr)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974],
       [2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
        3.        ],
       [2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
        3.46410162]])

In [28]:
#Taking the dot product of the first row and the second row

np.dot(two_d_arr[0,0:], #Slice row 0
      two_d_arr[1,0:])  #Slice row 1

154